import 'package:drift/drift.dart';

import '../../enums/app_enums.dart';
import '../app_database.dart';
import '../tables/master_tables.dart';
import '../tables/opname_tables.dart';

part 'opname_dao.g.dart';

/// A Stok Opname header joined with everything a list row needs to render.
class OpnameWithContext {
  const OpnameWithContext({
    required this.opname,
    required this.room,
    required this.branch,
    required this.countedBy,
    this.reviewedBy,
    required this.lineCount,
    required this.differenceLineCount,
  });

  final StockOpnameRow opname;
  final Room room;
  final Branch branch;
  final AppUser countedBy;
  final AppUser? reviewedBy;
  final int lineCount;
  final int differenceLineCount;
}

/// The four columns [OpnameDao.accessScope] returns — everything an
/// authorization check needs and nothing else.
class StockOpnameAccessRow {
  const StockOpnameAccessRow({
    required this.opnameId,
    required this.branchId,
    required this.status,
    required this.countedBy,
  });

  final String opnameId;
  final String branchId;
  final StockOpnameStatus status;
  final String countedBy;
}

/// One opname line joined with its item and — for expiry-tracked items — batch.
class OpnameLineWithDetails {
  const OpnameLineWithDetails({
    required this.line,
    required this.item,
    this.batch,
  });

  final StockOpnameLineRow line;
  final Item item;
  final ItemBatch? batch;
}

/// Stok Opname persistence.
///
/// Three deliberate absences shape this API:
///
/// * **No unrestricted update.** Every write that changes a document or one of
///   its lines is guarded by the parent's status, so a stale screen or a racing
///   device can never edit a `submitted` or `reviewed` document (G-S2). Each
///   guarded write returns the number of affected rows; zero means the guard
///   fired and the caller must raise a state failure.
/// * **No hard delete for final documents.** `softDeleteDraft` refuses anything
///   that is not a draft (G-A5).
/// * **No `system_qty` writer.** The snapshot is set once at insert and there
///   is no code path that can change it afterwards (G-O2).
///
/// Like the inventory DAO, this is a milli-unit layer (Q-4): `system_qty`,
/// `counted_qty` and `difference` are INTEGER columns holding `unit * 1000`.
/// The repository above converts them to `Quantity`.
@DriftAccessor(
  tables: [
    StockOpnames,
    StockOpnameLines,
    Items,
    ItemBatches,
    Rooms,
    Branches,
    Users,
  ],
)
class OpnameDao extends DatabaseAccessor<AppDatabase> with _$OpnameDaoMixin {
  OpnameDao(super.db);

  // --- writes ---------------------------------------------------------------

  Future<StockOpnameRow> insertHeader(StockOpnamesCompanion header) =>
      into(stockOpnames).insertReturning(header);

  /// Inserts the whole snapshot in one statement batch. Callers run this inside
  /// the same transaction as [insertHeader] so a header can never exist without
  /// its lines.
  Future<void> insertLines(List<StockOpnameLinesCompanion> lines) async {
    if (lines.isEmpty) return;
    await batch((b) => b.insertAll(stockOpnameLines, lines));
  }

  /// Adds one line to a document that is still a draft.
  ///
  /// Returns `null` when the parent is not an editable draft.
  ///
  /// The status check and the insert run in one transaction. Without it they
  /// are two statements with a gap between them, and a submit committing in
  /// that gap would let this insert land on an already-submitted document —
  /// a line appearing on a document nobody can edit any more (G-S2).
  Future<StockOpnameLineRow?> insertDraftLine({
    required String opnameId,
    required StockOpnameLinesCompanion line,
  }) {
    return transaction(() async {
      if (!await isDraft(opnameId)) return null;
      return into(stockOpnameLines).insertReturning(line);
    });
  }

  /// Updates the counted quantity and note of one draft line.
  ///
  /// The `opname_id IN (SELECT ...)` guard is evaluated by SQLite in the same
  /// statement as the write, so there is no window between checking the status
  /// and applying the change. Returns the number of updated rows: 0 means the
  /// line is gone or its document is no longer a draft.
  ///
  /// `system_qty` is not in the SET list, and `difference` is generated by the
  /// database — both are therefore untouchable from here (G-O2).
  Future<int> updateDraftLine({
    required String lineId,
    required int countedQtyMilliUnits,
    required String? note,
  }) {
    return customUpdate(
      'UPDATE stock_opname_lines '
      'SET counted_qty = ?, note = ?, updated_at = ?, sync_status = ? '
      'WHERE id = ? AND deleted_at IS NULL AND opname_id IN ('
      '  SELECT id FROM stock_opnames '
      "  WHERE status = 'draft' AND deleted_at IS NULL"
      ');',
      variables: [
        Variable<int>(countedQtyMilliUnits),
        Variable<String>(note),
        Variable<DateTime>(DateTime.now().toUtc()),
        Variable<String>(SyncStatus.pending.dbValue),
        Variable<String>(lineId),
      ],
      updates: {stockOpnameLines},
      updateKind: UpdateKind.update,
    );
  }

  /// Soft-deletes a line that was added to a draft by mistake. Guarded exactly
  /// like [updateDraftLine]; lines of submitted or reviewed documents survive
  /// every call.
  Future<int> softDeleteDraftLine(String lineId) {
    return customUpdate(
      'UPDATE stock_opname_lines '
      'SET deleted_at = ?, updated_at = ?, sync_status = ? '
      'WHERE id = ? AND deleted_at IS NULL AND opname_id IN ('
      '  SELECT id FROM stock_opnames '
      "  WHERE status = 'draft' AND deleted_at IS NULL"
      ');',
      variables: [
        Variable<DateTime>(DateTime.now().toUtc()),
        Variable<DateTime>(DateTime.now().toUtc()),
        Variable<String>(SyncStatus.pending.dbValue),
        Variable<String>(lineId),
      ],
      updates: {stockOpnameLines},
      updateKind: UpdateKind.update,
    );
  }

  /// Moves a document from [from] to [to], but only if it is still in [from].
  ///
  /// This is the only status writer, and it never accepts a free-form update:
  /// the caller states which transition it believes it is making, and the
  /// `WHERE status = from` clause makes a lost update impossible. A return
  /// value of 0 means somebody else moved the document first.
  Future<int> transitionStatus({
    required String opnameId,
    required StockOpnameStatus from,
    required StockOpnameStatus to,
    DateTime? submittedAt,
    DateTime? reviewedAt,
    String? reviewedBy,
  }) {
    return (update(stockOpnames)..where(
          (t) =>
              t.id.equals(opnameId) &
              t.status.equalsValue(from) &
              t.deletedAt.isNull(),
        ))
        .write(
          StockOpnamesCompanion(
            status: Value(to),
            // Forced to UTC here rather than trusted from the caller (T-1).
            // Drift serialises a non-UTC DateTime with an offset suffix
            // (`…+08:00`) instead of `…Z`, so a value that arrived in
            // operational time would be *stored* as a different instant than
            // the one the domain validated. Ordering itself is no longer a
            // database concern — schema v4 dropped the lexical
            // `reviewed_at >= submitted_at` CHECK and
            // `DocumentTimestampPolicy` decides it on UTC instants instead.
            submittedAt: submittedAt == null
                ? const Value.absent()
                : Value(submittedAt.toUtc()),
            reviewedAt: reviewedAt == null
                ? const Value.absent()
                : Value(reviewedAt.toUtc()),
            reviewedBy: reviewedBy == null
                ? const Value.absent()
                : Value(reviewedBy),
            updatedAt: Value(DateTime.now().toUtc()),
            // Once the document leaves the device it is the server's to
            // confirm (G-Y2), so every transition queues a sync.
            syncStatus: const Value(SyncStatus.pending),
          ),
        );
  }

  /// Soft-deletes a draft. Submitted and reviewed documents are permanent
  /// (G-S2/G-A5) and this guard is what makes the workflow unable to remove
  /// them.
  Future<int> softDeleteDraft(String opnameId) {
    return (update(stockOpnames)..where(
          (t) =>
              t.id.equals(opnameId) &
              t.status.equalsValue(StockOpnameStatus.draft) &
              t.deletedAt.isNull(),
        ))
        .write(
          StockOpnamesCompanion(
            deletedAt: Value(DateTime.now().toUtc()),
            updatedAt: Value(DateTime.now().toUtc()),
            syncStatus: const Value(SyncStatus.pending),
          ),
        );
  }

  // --- reads ----------------------------------------------------------------

  Future<StockOpnameRow?> headerById(String id) => (select(
    stockOpnames,
  )..where((t) => t.id.equals(id) & t.deletedAt.isNull())).getSingleOrNull();

  /// The four columns that decide whether somebody may open this document.
  ///
  /// Deliberately not `headerById`, and deliberately not the joined summary:
  /// an authorization check must not be the reason a foreign document's room,
  /// nurse, line count or document number is read out of the database. The
  /// `branch_id` predicate is in the statement rather than applied afterwards,
  /// so a row from another branch never leaves SQLite at all — the caller
  /// cannot leak what it never received.
  ///
  /// Returns `null` both for "no such document" and for "not this branch", and
  /// that ambiguity is the point (§6.5).
  Future<StockOpnameAccessRow?> accessScope({
    required String opnameId,
    required String branchId,
  }) async {
    final row =
        await (selectOnly(stockOpnames)
              ..addColumns([
                stockOpnames.id,
                stockOpnames.branchId,
                stockOpnames.status,
                stockOpnames.countedBy,
              ])
              ..where(
                stockOpnames.id.equals(opnameId) &
                    stockOpnames.branchId.equals(branchId) &
                    stockOpnames.deletedAt.isNull(),
              ))
            .getSingleOrNull();
    if (row == null) return null;

    return StockOpnameAccessRow(
      opnameId: row.read(stockOpnames.id)!,
      branchId: row.read(stockOpnames.branchId)!,
      status: row.readWithConverter(stockOpnames.status)!,
      countedBy: row.read(stockOpnames.countedBy)!,
    );
  }

  Future<bool> isDraft(String opnameId) async {
    final row = await headerById(opnameId);
    return row?.status == StockOpnameStatus.draft;
  }

  /// The weekly key behind G-O1. Returns the existing document for this room
  /// and ISO week, if any.
  Future<StockOpnameRow?> findForRoomAndPeriod({
    required String roomId,
    required int periodYear,
    required int periodWeek,
  }) {
    return (select(stockOpnames)..where(
          (t) =>
              t.roomId.equals(roomId) &
              t.periodYear.equals(periodYear) &
              t.periodWeek.equals(periodWeek) &
              t.deletedAt.isNull(),
        ))
        .getSingleOrNull();
  }

  Future<List<StockOpnameLineRow>> linesOf(String opnameId) => (select(
    stockOpnameLines,
  )..where((t) => t.opnameId.equals(opnameId) & t.deletedAt.isNull())).get();

  /// The item id of every live line, read **without joining `items`**.
  ///
  /// [detailLines] inner-joins the item so a line can render its name and
  /// unit, which means a line whose item row is physically gone silently
  /// vanishes from the result instead of raising anything. On a draft that is
  /// merely wrong; on a review it would post a *subset* of the counted
  /// positions and lock the document as if it had been done in full. This
  /// query is the honest count the review checks itself against — the join can
  /// hide a row, a plain select cannot.
  ///
  /// Duplicates are expected and meaningful: an expiry item is counted once per
  /// batch.
  Future<List<String>> lineItemIds(String opnameId) async {
    final rows =
        await (selectOnly(stockOpnameLines)
              ..addColumns([stockOpnameLines.itemId])
              ..where(
                stockOpnameLines.opnameId.equals(opnameId) &
                    stockOpnameLines.deletedAt.isNull(),
              ))
            .get();
    return rows
        .map((row) => row.read(stockOpnameLines.itemId)!)
        .toList(growable: false);
  }

  Future<StockOpnameLineRow?> lineById(String id) => (select(
    stockOpnameLines,
  )..where((t) => t.id.equals(id) & t.deletedAt.isNull())).getSingleOrNull();

  /// Whether this item/batch already has a line on the document — the check
  /// behind "do not add the same position twice".
  Future<StockOpnameLineRow?> findLine({
    required String opnameId,
    required String itemId,
    String? batchId,
  }) {
    return (select(stockOpnameLines)..where(
          (t) =>
              t.opnameId.equals(opnameId) &
              t.itemId.equals(itemId) &
              (batchId == null
                  ? t.batchId.isNull()
                  : t.batchId.equals(batchId)) &
              t.deletedAt.isNull(),
        ))
        .getSingleOrNull();
  }

  JoinedSelectStatement<HasResultSet, dynamic> _detailLinesQuery(
    String opnameId,
  ) {
    return select(stockOpnameLines).join([
        innerJoin(items, items.id.equalsExp(stockOpnameLines.itemId)),
        leftOuterJoin(
          itemBatches,
          itemBatches.id.equalsExp(stockOpnameLines.batchId),
        ),
      ])
      ..where(
        stockOpnameLines.opnameId.equals(opnameId) &
            stockOpnameLines.deletedAt.isNull(),
      )
      ..orderBy([
        OrderingTerm.asc(items.name),
        OrderingTerm.asc(itemBatches.expiryDate),
        OrderingTerm.asc(itemBatches.batchNo),
      ]);
  }

  List<OpnameLineWithDetails> _mapLines(List<TypedResult> rows) {
    return rows
        .map(
          (row) => OpnameLineWithDetails(
            line: row.readTable(stockOpnameLines),
            item: row.readTable(items),
            batch: row.readTableOrNull(itemBatches),
          ),
        )
        .toList(growable: false);
  }

  Future<List<OpnameLineWithDetails>> detailLines(String opnameId) async =>
      _mapLines(await _detailLinesQuery(opnameId).get());

  Stream<List<OpnameLineWithDetails>> watchDetailLines(String opnameId) =>
      _detailLinesQuery(opnameId).watch().map(_mapLines);

  // The reviewer is joined through a second alias of `users`, because a
  // document references two different people.
  late final $UsersTable _reviewers = alias(users, 'reviewer');

  // Both counters filter soft-deleted lines explicitly. The join below already
  // excludes them, so this is redundant today — but stating it in each
  // aggregate keeps the two from silently disagreeing if that join changes.
  Expression<int> get _lineCount =>
      stockOpnameLines.id.count(filter: stockOpnameLines.deletedAt.isNull());

  Expression<int> get _differenceLineCount => stockOpnameLines.id.count(
    filter:
        stockOpnameLines.difference.isNotValue(0) &
        stockOpnameLines.deletedAt.isNull(),
  );

  JoinedSelectStatement<HasResultSet, dynamic> _summaryQuery(
    Expression<bool> predicate,
  ) {
    final query = (select(stockOpnames)..where((t) => t.deletedAt.isNull()))
        .join([
          innerJoin(rooms, rooms.id.equalsExp(stockOpnames.roomId)),
          innerJoin(branches, branches.id.equalsExp(stockOpnames.branchId)),
          innerJoin(users, users.id.equalsExp(stockOpnames.countedBy)),
          leftOuterJoin(
            _reviewers,
            _reviewers.id.equalsExp(stockOpnames.reviewedBy),
          ),
          // Left join so a document with no lines still produces a row, and
          // soft-deleted lines never inflate the counts.
          leftOuterJoin(
            stockOpnameLines,
            stockOpnameLines.opnameId.equalsExp(stockOpnames.id) &
                stockOpnameLines.deletedAt.isNull(),
          ),
        ]);

    return query
      ..addColumns([_lineCount, _differenceLineCount])
      ..where(predicate)
      ..groupBy([stockOpnames.id])
      ..orderBy([
        OrderingTerm.desc(stockOpnames.periodYear),
        OrderingTerm.desc(stockOpnames.periodWeek),
        OrderingTerm.asc(rooms.code),
      ]);
  }

  List<OpnameWithContext> _mapSummaries(List<TypedResult> rows) {
    return rows
        .map(
          (row) => OpnameWithContext(
            opname: row.readTable(stockOpnames),
            room: row.readTable(rooms),
            branch: row.readTable(branches),
            countedBy: row.readTable(users),
            reviewedBy: row.readTableOrNull(_reviewers),
            lineCount: row.read(_lineCount) ?? 0,
            differenceLineCount: row.read(_differenceLineCount) ?? 0,
          ),
        )
        .toList(growable: false);
  }

  /// The document predicate, optionally pinned to one branch.
  ///
  /// When [branchId] is supplied the check happens **inside the statement**, so
  /// a document from another branch is never read, never mapped and never
  /// reaches a stream a widget could be listening to. Filtering the result in
  /// Dart would look equivalent and would not be: the row would already have
  /// been fetched, and every later refactor would be one `if` away from
  /// emitting it.
  Expression<bool> _document(String opnameId, String? branchId) {
    final byId = stockOpnames.id.equals(opnameId);
    return branchId == null
        ? byId
        : byId & stockOpnames.branchId.equals(branchId);
  }

  Future<OpnameWithContext?> summaryById(
    String opnameId, {
    String? branchId,
  }) async {
    final rows = await _summaryQuery(_document(opnameId, branchId)).get();
    return rows.isEmpty ? null : _mapSummaries(rows).single;
  }

  Stream<OpnameWithContext?> watchSummaryById(
    String opnameId, {
    String? branchId,
  }) {
    return _summaryQuery(
      _document(opnameId, branchId),
    ).watch().map((rows) => rows.isEmpty ? null : _mapSummaries(rows).single);
  }

  Expression<bool> _scope({
    String? branchId,
    String? roomId,
    String? countedBy,
    Set<StockOpnameStatus> statuses = const {},
  }) {
    var predicate = const Constant(true) as Expression<bool>;
    if (branchId != null) {
      predicate = predicate & stockOpnames.branchId.equals(branchId);
    }
    if (roomId != null) {
      predicate = predicate & stockOpnames.roomId.equals(roomId);
    }
    if (countedBy != null) {
      predicate = predicate & stockOpnames.countedBy.equals(countedBy);
    }
    if (statuses.isNotEmpty) {
      predicate =
          predicate &
          stockOpnames.status.isIn(
            statuses.map((status) => status.dbValue).toList(growable: false),
          );
    }
    return predicate;
  }

  Future<List<OpnameWithContext>> listOpnames({
    String? branchId,
    String? roomId,
    String? countedBy,
    Set<StockOpnameStatus> statuses = const {},
  }) async {
    final rows = await _summaryQuery(
      _scope(
        branchId: branchId,
        roomId: roomId,
        countedBy: countedBy,
        statuses: statuses,
      ),
    ).get();
    return _mapSummaries(rows);
  }

  Stream<List<OpnameWithContext>> watchOpnames({
    String? branchId,
    String? roomId,
    String? countedBy,
    Set<StockOpnameStatus> statuses = const {},
  }) {
    return _summaryQuery(
      _scope(
        branchId: branchId,
        roomId: roomId,
        countedBy: countedBy,
        statuses: statuses,
      ),
    ).watch().map(_mapSummaries);
  }

  /// Items and batches a nurse may add to a draft, filtered the same way the
  /// SearchableDropdown filters (name or SKU, case-insensitive, optional
  /// category). Runs entirely against the local database, so it works offline
  /// (G-Y1).
  Future<List<Item>> searchAddableItems({
    required String query,
    String? categoryId,
    int limit = 8,
  }) {
    final pattern = '%${query.trim().toLowerCase()}%';
    return (select(items)
          ..where(
            (t) =>
                t.deletedAt.isNull() &
                t.isActive.equals(true) &
                (t.name.lower().like(pattern) | t.sku.lower().like(pattern)) &
                (categoryId == null
                    ? const Constant(true)
                    : t.categoryId.equals(categoryId)),
          )
          ..orderBy([(t) => OrderingTerm.asc(t.name)])
          ..limit(limit))
        .get();
  }

  Future<int> countDifferenceLines(String opnameId) async {
    final expr = stockOpnameLines.id.count();
    final row =
        await (selectOnly(stockOpnameLines)
              ..addColumns([expr])
              ..where(
                stockOpnameLines.opnameId.equals(opnameId) &
                    stockOpnameLines.deletedAt.isNull() &
                    stockOpnameLines.difference.isNotValue(0),
              ))
            .getSingle();
    return row.read(expr) ?? 0;
  }
}
